// Backlog #39 (SITE-005): store-wide product search.
// The index is /search-index.json, regenerated by scripts/generate-pages.mjs
// on every publish -- one compact entry per filament colour, category item,
// and navigable page: { t: type label, n: name, s: sku, k: keywords,
// h: root-relative href (with item anchor), p: display price }.
// All matching is client-side; the catalogue is a few hundred entries.

let indexPromise = null;
function loadIndex() {
  if (!indexPromise) {
    indexPromise = fetch('/search-index.json', { cache: 'no-store' })
      .then((r) => (r.ok ? r.json() : []))
      .catch(() => []);
  }
  return indexPromise;
}

export async function searchSite(query) {
  const q = String(query || '').trim().toLowerCase();
  if (q.length < 2) return [];
  const index = await loadIndex();
  return index
    .map((e) => {
      const name = (e.n || '').toLowerCase();
      const sku = (e.s || '').toLowerCase();
      const kw = (e.k || '').toLowerCase();
      let score = 0;
      if (sku && sku === q) score = 5;
      else if (sku && sku.includes(q)) score = 3;
      else if (name.startsWith(q)) score = 3;
      else if (name.includes(q)) score = 2;
      else if (kw.includes(q)) score = 1;
      return { entry: e, score };
    })
    .filter((r) => r.score > 0)
    .sort((a, b) => b.score - a.score)
    .slice(0, 10)
    .map((r) => r.entry);
}

// Renders results into `container` as clickable rows; hrefs in the index
// are root-relative, prefixed here for the current page depth. The
// no-results state routes to the custom-quote flow rather than dead-ending.
export function attachSearch(input, container) {
  if (!input || !container) return;
  const depth = (window.__PAGE_DEPTH__ ?? 0) | 0;
  const prefix = '../'.repeat(depth);
  let seq = 0;

  async function render() {
    const mySeq = ++seq;
    const q = input.value.trim();
    container.textContent = '';
    if (q.length < 2) return;
    const results = await searchSite(q);
    if (mySeq !== seq) return; // a newer keystroke superseded this render
    if (!results.length) {
      const empty = document.createElement('p');
      empty.className = 'text-espresso/50 px-2 py-2 text-sm';
      empty.textContent = 'No matches — ';
      const a = document.createElement('a');
      a.href = `${prefix}design-request.html`;
      a.className = 'text-terracotta font-semibold hover:underline';
      a.textContent = 'request it as a custom print';
      empty.appendChild(a);
      container.appendChild(empty);
      return;
    }
    results.forEach((e) => {
      const a = document.createElement('a');
      a.href = prefix + e.h;
      a.className = 'flex items-baseline justify-between gap-3 px-2 py-2 rounded-lg hover:bg-charcoal/5 transition-colors';
      const left = document.createElement('span');
      left.className = 'min-w-0 truncate text-sm';
      left.textContent = e.n;
      const right = document.createElement('span');
      right.className = 'shrink-0 text-xs text-espresso/50';
      right.textContent = e.p ? `${e.t} · ${e.p}` : e.t;
      a.append(left, right);
      container.appendChild(a);
    });
  }

  let timer = null;
  input.addEventListener('input', () => {
    clearTimeout(timer);
    timer = setTimeout(render, 120);
  });
  input.addEventListener('keydown', (e) => {
    if (e.key === 'Enter') {
      const first = container.querySelector('a');
      if (first) window.location.href = first.getAttribute('href');
    }
  });
}
